### ISSUE TITLE
Schedule refresh crashes on a non-string provider name or notes (conferenceChampionships.ts:39)

### ISSUE THREAD

**Issue by znpruitt** [znpruitt/cfb-app#848]
**What happens.** `mapCfbdScheduleGame` (`src/lib/schedule/cfbdSchedule.ts`) passes the raw provider `game.notes` / `game.name` into `matchConferenceChampionshipSlotByText`. That reaches `normalizeConferenceIdentity` (`src/lib/conferenceChampionships.ts:39`), which calls `(value ?? '').toLowerCase()`. A non-string value (for example a number) throws `TypeError: (value ?? "").toLowerCase is not a function`.

**Impact: loud and fail-safe, not silent.** The throw escapes the mapper, so the full-season schedule refresh fails for that partition and **nothing is stored**. No partial or wrong row reaches the durable schedule. The cost is availability: one bad provider value blocks that season's schedule refresh until CFBD corrects it.

**How it was found.** #813 v4's acceptance 8 (`src/lib/server/__tests__/durableScheduleRow.test.ts`) feeds adversarial values into every field of `CfbdScheduleGame` (all 66, compile-checked against the type), across the regular, conference-championship and playoff shapes and both season types, and asserts every row the mapper returns conforms to `ScheduleWireItem`. A throw stores nothing, so it is recorded separately from conformance.

**Exactly what is and isn't covered.** The test pins the set of provider fields whose adversarial values make the mapper **throw** as exactly `['name', 'notes']`. So:
- Any **new** throwing field fails that test, and so does fixing these two; the pinned line is then updated deliberately.
- Every other provider field, given every adversarial value in the test (numbers, booleans, `null`, objects, arrays, out-of-set strings, look-alike structured strings), either maps to a conforming row or is dropped by the mapper's existing rules.
- The adversarial values are a fixed list, not an exhaustive type-space search.

**Predates #813.** The raw pass-through is on `main` unchanged; #813 v4 did not introduce or alter it.

**Likely fix.** Normalise `name` / `notes` to strings (`normalizeString`, as the mapper already does for `label` and `notes` when *storing* them) before the conference-text match, then update the pinned set in the test to `[]`.

Out of scope for #813 v4 (owner ruling 2026-09-22).

**Comment by znpruitt** [comment]
**Parked 2026-09-22 — latent, and it fails safe.**

It needs CFBD to send a non-string `name` or `notes`. The crash is **loud and non-destructive**: nothing is stored and the refresh fails, so prior-good data is retained. #813 v4's acceptance-8 test pins the throwing set as exactly `name` and `notes`, so a new field joining that set surfaces in the suite rather than in production.

**Un-parking trigger:** a schedule-refresh failure whose receipt or log carries this TypeError.
